import React from "react";
import NewsSidebar from "../NewsSidebar";
import Link from "next/link";

const post_Albany_2023_2024 = () => {
  return (
    <>
      <section className="news-details-area ptb-100">
        <div className="container">
          <div className="row">
            <div className="col-lg-8 col-md-12">
              <div className="blog-details-desc">
                <div className="article-image">
                  <img
                    src="/images/blog-details/blog-details2.png"
                    alt="Image"
                  />
                </div>

                <div className="article-content">
                  <div className="entry-meta">
                    <ul>
                      <li>
                        <span>Posted On:</span> January 13, 2024
                      </li>
                    </ul>
                  </div>

                  <h3>
                    ALBANY ACADEMIES QUALIFIER
                  </h3>
                  
                  <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#ffffff;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;ABOUT THE TOURNAMENT</span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">FTC Team #4654, the Jellyfish, competed in their second qualifying tournament of the season on January 13th at the Albany Academies. The team made it all the way to finals, receiving the 1</span><span style="font-size:0.6em;vertical-align:super;;font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">st</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;place Inspire Award, 2</span><span style="font-size:0.6em;vertical-align:super;;font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">nd</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;place Think Award, and 3<span style="font-size:0.6em;vertical-align:super;">rd&nbsp;</span>place Design &nbsp;Award.<span class="Apple-tab-span" style="white-space:pre;">&nbsp; &nbsp; &nbsp;</span></span></p>
                  <p dir="ltr" style="line-height: 1.38; text-align: center; margin-top: 0pt; margin-bottom: 12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span class="Apple-tab-span" style="white-space:pre;">&nbsp; &nbsp; &nbsp; &nbsp;</span> <span style="border:none;display:inline-block;overflow:hidden;width:280px;height:172px;"><img src="https://lh7-us.googleusercontent.com/UyrB03JlZaJyKJwQRd4T23NJuSk0S6uTQhLMV_OQcOoiv6Y64ln53eEGcTEK10eOVAjj5LpoCdxnM7h4Ev3GXJHGplzdKIElpaD7oCjtuj-o7kSjqC1gH_HbwEweZ3UVR0kyuHk-_v5FzAFYvIZtX4A" width="280" height="172"/> </span></span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: center;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OUR ROBOT HANGING IN A GAME</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.</span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The team competes in the&nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">FIRST Tech Challenge&nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(FTC), where teams build and program robots to overcome specific obstacles and challenges. &nbsp;This season&rsquo;s game,&nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Centerstage</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, involves the robots picking up &ldquo;pixels&rdquo; and depositing them onto a slanted backdrop. Robots can also launch paper airplanes and hang from a truss in order to score more points.&nbsp;</span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">In Albany, the Jellyfish competed against twenty-seven other teams from across the New York-Excelsior region, which encompasses all of NY state barring the NYC and Long Island areas. Teams compete in randomly paired alliances of two, which encourages cooperation in the midst of competition &ndash; a key FIRST concept called &ldquo;Gracious Professionalism&rdquo;.&nbsp;</span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#ffffff;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;ABOUT THE TEAM</span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Jellyfish&rsquo;s driver crew consisted of co-presidents Taka Kimura and Joaquin Otero as robot drivers, assisted by Lead Programmer Jeffrey Kuo as their driver coach. Sophomore Jocelyn Zheng acted as the team&rsquo;s human player, making her the first non-senior of the season to participate in the driver crew.</span></p>
                  <p dir="ltr" style="line-height: 1.38; text-align: center; margin-top: 0pt; margin-bottom: 12pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:345px;height:230px;"><img src="https://lh7-us.googleusercontent.com/_yg2KeTgIx4DLh0tvhyuZ_4thvqQpcL5TfcPN-vO3mRYINv455DHpE667k0WlRRytS9mh4PN0kpKLsRddYUy728X7DTMSUdWTpVtUvknVWzFkSnbCs6x-SWMWLpwoNGmIi2ErsJhtptn1KZj6hMC6mo" width="345" height="230"/></span></span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></p>
                  <p dir="ltr" style="line-height: 1.38; text-align: center; margin-top: 0pt; margin-bottom: 12pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">JOAQUIN OTERO, JEFFREY KUO, AND TAKA KIMURA MID-MATCH.</span></p>
                  <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Jellyfish would also like to thank our advisor, Dr. Julie Kenyon! In addition to dedicating countless hours of her time to our team, she has been of immense help in coordinating team activities and efforts.</span></p>
                  <div dir="ltr" style="margin-left:0pt;" align="left">
                    <table style="border:none;border-collapse:collapse;">
                        <tbody>
                            <tr style="height:0pt;">
                                <td style="border-left:solid #ffffff 1pt;border-right:solid #ffffff 1pt;border-bottom:solid #ffffff 1pt;border-top:solid #ffffff 1pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"><span style="border:none;display:inline-block;overflow:hidden;width:403px;height:177px;"><img src="https://lh7-us.googleusercontent.com/Sr-ieGNgCo80rq3kTpJV9tbaBNU1sCb4D9LTINpoOq7rOPXueTD3i8P0F-sv6VydvQ_toLge-Wyvq2JyQIztKUAFVbTDe094NDP9eKZY5WyWqojFaemqSd13UXtJUNKO7-PaXOIP2YzrecuspShoJKw" width="538.5222738788535" height="405.78855165788167"/></span></td>
                                <td style="border-left:solid #ffffff 1pt;border-right:solid #ffffff 1pt;border-bottom:solid #ffffff 1pt;border-top:solid #ffffff 1pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;"><span style="border:none;display:inline-block;overflow:hidden;width:143px;height:176px;"><img src="https://lh7-us.googleusercontent.com/RsNt8d75Kuuwu6GiA5xCSSwF_v7zzx9-VUexol8Y4sq7ByuDJ-15k57hvb-caat9VRp1wjcNq0xI14RQn_AMQFOBkJu9Ur7RkPsSwpra4ee7kn4gJNsPGuuLq09z8xkCpycTmDpTMMGhUrcYsJwXcYs" width="300.44444444444446" height="229.7025050336791"/></span></td>
                            </tr>
                            <tr style="height:0pt;">
                                <td style="border-left:solid #ffffff 1pt;border-right:solid #ffffff 1pt;border-bottom:solid #ffffff 1pt;border-top:solid #ffffff 1pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;">
                                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">JELLYFISH SENIORS.</span></p>
                                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Lato,sans-serif;color:#5e81ac;background-color:transparent;font-weight:300;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Left to right: Jeffrey Kuo, Fiona Chen, Taira Nonami, Matthew Laterza, Ian Goldfeld, Taka Kimura, Joaquin Otero, Austin Lu, Jackson Welde, &amp; Alex Thompson</span></p>
                                </td>
                                <td style="border-left:solid #ffffff 1pt;border-right:solid #ffffff 1pt;border-bottom:solid #ffffff 1pt;border-top:solid #ffffff 1pt;vertical-align:top;padding:5pt 5pt 5pt 5pt;overflow:hidden;overflow-wrap:break-word;">
                                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">JELLYFISH SOPHOMORES.</span></p>
                                    <p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Lato,sans-serif;color:#5e81ac;background-color:transparent;font-weight:300;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Left to right: Jocelyn Zheng, Amrit Mohapatra, Martin Ayala, Abigail Weintraub</span></p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#ffffff;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;3</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;OUR ROBOT<span class="Apple-tab-span" style="white-space:pre;">&nbsp; &nbsp;&nbsp;</span></span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Following the Jellyfish tradition of naming our robots after influential women in STEM, this season&rsquo;s bot is named&nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Michele</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, after Dr. Michele Sugantino.&nbsp;</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Dr. Sugantino, affectionately nicknamed &ldquo;Doc&rdquo; by her students, taught chemistry for 18 years at our high school and pioneered our science research program.</span></p>
                <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The primary objective of our robot is to intake in pixels and dispense them onto the slanted backdrop.&nbsp;</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Our robot intakes pixels using wheels of silicone tubing, to push pixels up our CNC-cut aluminum ramp. We then deposit pixels using our custom 3D-printed outtake, which releases pixels in a &ldquo;garbage dump&rdquo; manner. Pixels can be deposited individually with the use of another gecko wheel. Our drivetrain is built with mecanum wheels, which allows our robot to move and strafe in all directions, regardless of its field orientation.</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:224px;"><img src="https://lh7-us.googleusercontent.com/eb6ekXbuNsHN6vwx0H1zR7Cy_wYsafvKj6kpbisSq-kl4u9Ri1crH1-T5REzKkbB95uoDJUCH-A4KdnpH9qJK8WKIRAONEoxgDWTvX2eP296ccoCOZESZxtaOCKljiImE2FakbsW6GJc5BM3qWeF0ow" width="624" height="224"/></span></span></p>
                <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">LEFT:</span><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;MICHELE FROM THE SIDE. HER VERTICAL SLIDES ARE HALF-EXTENDED, AND THE INTAKE RAMP IS RAISED.<br/></span></p>
                <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CENTER:</span><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;THE LOWERED INTAKE RAMP CONTAINING TWO ROWS OF SILICONE TUBING TO INTAKE PIXELS. <br/></span></p>
                <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">RIGHT:</span><span style="font-size:11pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;A CAD RENDER OF OUR CUSTOM OUTTAKE, DESIGNED TO INDIVIDUALLY DEPOSIT PIXELS WITH THE &ldquo;GARBAGE DUMP&rdquo; METHOD.</span></p>
                <p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#ffffff;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">4</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:#5e81ac;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;TOURNAMENT OUTCOME</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">FTC tournaments are split into two stages: Qualification, where every team plays five matches; and Finals, where finalist alliances are eliminated from the competition after losing .</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:20pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:600;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">QUALIFICATION MATCHES</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Jellyfish went 3-2 in our qualification matches, finishing in 9th place overall. We briefly held the tournament record for highest number of non-penalty points scored in a match.</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:20pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:600;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">FINALS</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We were selected to the first seed alliance, captained by&nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Team 6955 RoBovines,</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;along with&nbsp;</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Team 8397 Beta</span><span style="font-size:15pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">. Together, we swept our way through semifinals and set a new NY-Excelsior region record. Though we won our finals match, winners were determined in a best-of-three manner, and our broader alliance lost 1-2.</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:20pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:600;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">AWARDS</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We won the following awards at the competition:</span></p>
                <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                    <li dir="ltr" style="list-style-type:disc;font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1">
                        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Inspire Award&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#5e81ac;background-color:transparent;font-weight:700;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1st Place</span></p>
                    </li>
                    <li dir="ltr" style="list-style-type:disc;font-size:16pt;font-family:Lato,sans-serif;color:#5e81ac;background-color:transparent;font-weight:700;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1">
                        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Think Award&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2nd place</span></p>
                    </li>
                    <li dir="ltr" style="list-style-type:disc;font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1">
                        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Design Award&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3rd place</span></p>
                    </li>
                    <li dir="ltr" style="list-style-type:disc;font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1">
                        <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finalist Alliance Member</span></p>
                    </li>
                </ul>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Through the 1</span><span style="font-size:0.6em;vertical-align:super;;font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">st&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">place Inspire Award, we qualified for the&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">New York-Excelsior Regional Championship</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, which will take place on March 3rd at the Mohawk Valley Community College in Utica, New York.</span></p>
                <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:30pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:600;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">THANK YOU TO OUR SPONSORS!</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:160px;"><img src="https://lh7-us.googleusercontent.com/eECgiHDrkema-A7cqJAPL5QaDn9OYMtbAkGQ5cX-CJdcOj3diqw2a3csY3HYXsEMzpVXsNe_vNVXfMU7Eg6CMCXE3-DwqlVKg3H4tVO5ILC2xb6aKMT07lIikVFpXvkqssZ9hgh7Q2a3kTFDsFGzZI4" width="624" height="160"/></span></span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:20pt;font-family:'IBM Plex Mono',monospace;color:#5e81ac;background-color:transparent;font-weight:600;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">UPCOMING TEAM EVENT DATES:</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Peekskill Qualifier:&nbsp;</span><span style="font-size: 20px; font-family: Lato, sans-serif; color: rgb(119, 119, 119); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Saturday, February 10</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 20px; font-family: Lato, sans-serif; color: rgb(119, 119, 119); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1072 Elm St, Peekskill, NY 10566&nbsp;</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">NY Excelsior Regional MVCC Championship:&nbsp;</span><span style="font-size: 20px; font-family: Lato, sans-serif; color: rgb(119, 119, 119); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Sunday, March 3</span><span style="font-size: 20px; font-family: Lato, sans-serif; color: rgb(46, 52, 64); background-color: transparent; font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 20px; font-family: Lato, sans-serif; color: rgb(119, 119, 119); background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1101 Sherman Dr, Utica, NY 13501<span class="Apple-tab-span" style="white-space: pre;">&nbsp; &nbsp;&nbsp;</span></span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Spring Junior Jellies session begins:&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#777777;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Spring 2024 - Date TBD!</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#777777;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Blind Brook Middle/High School</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16.5pt;font-family:Roboto,sans-serif;color:#1f1f1f;background-color:#ffffff;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Creaticon</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#2e3440;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">:&nbsp;</span><span style="font-size:16pt;font-family:Lato,sans-serif;color:#777777;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Tuesday, May 16</span></p>
                <p dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:16pt;font-family:Lato,sans-serif;color:#777777;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Blind Brook Middle/High School</span></p>
                </div>

                <div className="post-navigation">
                  <div className="navigation-links">
                    <div className="nav-previous">
                      <Link href="/news/centerstage">
                        <i className="bx bx-left-arrow-alt"></i> Prev Post
                      </Link>
                    </div>

                    <div className="nav-next">
                      <Link href="#">
                        Next Post <i className="bx bx-right-arrow-alt"></i>
                      </Link>
                    </div>
                  </div>
                </div>

                {}
              </div>
            </div>

            <div className="col-lg-4 col-md-12">
              <NewsSidebar />
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default post_Albany_2023_2024;